# Utiliser une image Python officielle comme base
FROM python:3.9

# Mettre à jour le gestionnaire de paquets et installer les outils nécessaires
RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean

# Installer Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier pyproject.toml pour installer les dépendances
COPY  . .

# Installer les dépendances du projet
RUN poetry install

# Install gunicorn
pip install gunicorn

# Run gunicorn with 4 threads on port 8080
gunicorn --workers 4 --bind 0.0.0.0:8080 image_api.web:app

# Copier le reste des fichiers de l'application
COPY . /app

# Exposer le port 8080 utilisé par l'application Flask
EXPOSE 8080

# Commande par défaut pour exécuter le serveur web avec Gunicorn
CMD ["gunicorn", "--workers", "4", "--bind", "0.0.0.0:8080", "image_api.web:app"]
