  image: docker:latest

  services:
    - docker:dind

  variables:
    DOCKER_DRIVER: overlay2

  before_script:
    - echo "dckr_pat_6ozrng5x5m16k68os4kQkO17NqI" > docker login -u "jbunistra" --password-stdin

  build:
    stage: build
    script:
      - docker build -t cloud-front-end:latest .
      - docker push  docker.io/jbunistra/cloud-front-end:latest

  
