---
# tasks file for consul

#- name: Import assert.yml
#  ansible.builtin.import_tasks:
#    file: assert.yml
#  run_once: true
#  delegate_to: localhost

- name: Install consul
  ansible.builtin.package:
    name: consul
    state: present
  when:
    - consul_install_package

- name: Create consul data directory
  ansible.builtin.file:
    path: "{{ consul_data_dir }}"
    state: directory
    owner: consul
    group: consul
    mode: "0750"

#- name: Create consul.env
#  ansible.builtin.file:
#    path: /etc/consul.d/consul.env
#    state: touch
#    owner: consul
#    group: consul
#    mode: "0644"
#    modification_time: preserve
#    access_time: preserve

- name: "Add group 'consul'"
  ansible.builtin.group:
    name: consul
    state: present

- name: "Add user 'consul'"
  ansible.builtin.user:
    name: consul
    group: consul
    home: /opt/consul
    create_home: true
    system: true
    shell: /bin/false
    state: present

- name: "Deploy Consul systemd service"
  ansible.builtin.copy:
    src: consul.service
    dest: /etc/systemd/system/consul.service
  notify: Reload systemd

- name: "Deploy the configuration"
  ansible.builtin.template:
    src: consul.hcl
    dest: /etc/consul.d/consul.hcl
  notify: Restart Consul


- name: Start and enable consul
  ansible.builtin.service:
    name: consul
    state: started
    enabled: true
  when:
    - consule_service_started_and_enabled