---
- name: "Add group 'nomad'"
  ansible.builtin.group:
    name: nomad
    state: present

- name: "Add user 'nomad'"
  ansible.builtin.user:
    name: nomad
    group: nomad
    home: /opt/nomad
    create_home: true
    system: true
    shell: /bin/false
    state: present

- name: Create /etc/nomad.d
  ansible.builtin.file:
    path: /etc/nomad
    state: directory
    mode: "0750"
    owner: nomad
    group: nomad

- name: Add Nomad Server Configuration File
  ansible.builtin.template:
    src: nomad.hcl
    dest: /etc/nomad.d/nomad.hcl
    owner: nomad
  tags:
    - install-nomad
    - configure

- name: "Create Nomad job directory"
  ansible.builtin.file:
    path: /etc/nomad.d/jobs/
    owner: nomad
    group: nomad
    state: directory

- name: "Copy job configuration file"
  ansible.builtin.template:
    src: templates/job.hcl
    dest: /etc/nomad.d/jobs/job.hcl
    owner: nomad
    group: nomad
    mode: "0644"

- name: "Deploy the Nomad configuration"
  ansible.builtin.template:
    src: nomad.hcl
    dest: /etc/nomad.d/nomad.hcl
  notify: Restart Nomad

- name: "Deploy Nomad systemd service"
  ansible.builtin.template:
    src: nomad.service
    dest: /etc/systemd/system/nomad.service
  notify: Reload systemd

- include_tasks: server.yml
  when: is_server

- ansible.builtin.meta: flush_handlers

