---

#- name: Import assert.yml
#  ansible.builtin.import_tasks:
#    file: assert.yml
#  run_once: true
#  delegate_to: localhost

#- name: Install nomad
#  ansible.builtin.package:
#    name: nomad
#    state: present
#  when:
#    - nomad_install_package

#configure nomad
- import_tasks: configure.yml

- name: "Enable and start Nomad"
  ansible.builtin.systemd:
    name: nomad.service
    enabled: true
    state: started

- name: "Restart Nomad"
  ansible.builtin.systemd:
    name: nomad.service
    state: restarted

- name: Determine nomad leader
  ansible.builtin.set_fact:
    nomad_leader: "{{ ansible_hostname }}"
  run_once: true
  when:
    - nomad_server
#
#- name: List server members
#  ansible.builtin.command:
#    cmd: nomad server members
#  register: nomad_list_server_members
#  changed_when: false
#  when:
#    - nomad_server

- name: Join nomad leader
  ansible.builtin.command:
    cmd: nomad server join {{ nomad_leader }}:4648
  register: nomad_join_nomad_leader
  when:
    - ansible_hostname != nomad_server
    - ansible_hostname not in nomad_list_server_members.stdout
  changed_when: true

- name: "Submit Nomad job"
  command: nomad run /etc/nomad.d/jobs/job.hcl
  delegate_to: "{{ job_instance_loader }}"
  become: true
  timeout: 300