---
- hosts: all
  become: yes
  become_user: root
  become_method: su
  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
  roles:
    - role: docker
      tags: docker
    - role: consul
      tags: consul
    - role: nomad
      tags: nomad